language: java
env:
  global:
  - GITHUB_REPO=symbiote-h2020/RegistrationHandlerClientStarter$
  - secure: U9f+nhCzbxiZ2GC3bI5/UI+ZrxpJHGpk0fWaJaQGOQFP2yk8AMnV5atkGhdRhNUvmUSIsh6sxR9+53Gr6K2rWC3wcGrQJW145i+jd7pII/IItnD+ftqDzKFcUOS7n2TFv3RkOZsfYeFhA8M0zcfnYRex8aLJsem8YHYAO83fvZq/C90wwDcpeuUMyYGNkEXeZip5fOxjVZ7zn1UT0FI3XGQ/mSyRn7psEkMpTnCvV9w1/h/SU4+2aCyWzjbc7jmEqRQNQSKM7jtqEfpkM0HQrHLIwpGfysCk9g2usHa/RRRwEPWqnlLZTY29od+vj4ulwcZA07Gr64pCBRGEuacYp2ZY3jmLpn8aZ2N9g+LWl+MkI6El4sCPJnG2vslkSCbd5YTQ+v3r2mEydf9kYLP5f2dtUrmLLKpaEDLb/XSGNJwbokzY0v7gtNb7GFqrk9JXwl9cPRo7rDknDYdsLWFa3HHN9LT6JE4/dT20ihxSKTDDz1BpbjcFUZLszSLiP50b0WH3mRu3pQkdgsxG8Mztnd582LOTF5E8zeJFukPZMr4VWNM3YAEjeMNCQVz7husJ6+61qh/0s8brFtPbxBg20Se8RE8uRSMn3CuahI9oJ8/BOcn5P/tSB6bGT1zD+FJMrTxdVKQmp985x4xhby+GlPdmLHIVxu6unD3ggZql7NU=
jdk:
- oraclejdk8
services:
- mongodb
sudo: required
branches:
  only:
  - staging
install: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_script:
- chmod a+x merge_script.sh
- "./merge_script.sh"
after_success:
- chmod a+x pushing_script.sh
- "./pushing_script.sh"
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
